cabal-version:       2.4
name:                banco-investimentos-haskell
version:             0.1.0.0
license:             BSD-3-Clause
license-file:        LICENSE
extra-source-files:  CHANGELOG.md

library
  exposed-modules:   Tipos, Logica  
       
  other-modules:       
  hs-source-dirs:      src
  build-depends:       base ^>=4.12.0.0,
                       aeson,
                       text,
                       containers,
                       bytestring,
                       time
  default-language:    Haskell2010

executable banco-investimentos-haskell-exe
  main-is:           Main.hs
  hs-source-dirs:    app
  build-depends:     base ^>=4.12.0.0,
                     banco-investimentos-haskell,
                     aeson,
                     text,
                     containers,
                     bytestring,
                     time
  default-language:    Haskell2010